### ISSUE TITLE
Incomplete line 1030 in file t119bruteforcerupdated.sub

### ISSUE THREAD

**Issue by S474N** [xb8/t119bruteforcer#1]
There is incomplete line 1030 (last line) in file `t119bruteforcerupdated.sub`:

![image](https://user-images.githubusercontent.com/16512337/185376905-c7f39d85-0b67-4ce4-a378-58e9d05ab079.png)

There is error in Flipper Zero device:
![image](https://user-images.githubusercontent.com/16512337/185376972-8272b4f5-2647-4305-b907-e03dcc9db9dd.png)

After manual deleting the line is everything ok.

**Comment by xb8** [comment]
line is there so you can plot the file, and the signal works correctly with it too. If it doesnt i suggest rewriting the file on the flipper that's probably it
