### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by nicpalmer30** [xb8/t119bruteforcer#3]
which file do I install and how do I install it?

**Comment by marnall** [comment]
@nicpalmer30  It uses the 433MHz module so I recommend putting it in the subghz folder of the root of your sdcard

**Comment by m0veax** [comment]
Regarding to the twitter links, they updated the Bruteforcer. This is the newest file in the repository, I'll try that:

https://github.com/xb8/t119bruteforcer/blob/main/t119bruteforcerupdated.sub
